# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cba2ccdf600c2608fefdf0764adc7ceb1844653fcf0db6c86d903e2d3c6fcf498cf8140f36704cf36a4e10908d63320295250c61c647171a564dc2df3f90c8d

test:
  secret_key_base: 059af456992271d9eb9f9a5ca5c80960b1e83b3dc719fbcfe039e3e73fd1c36d4c4f137e33282fbccea0563ff955a590afad3e12c4f732849fb84b8761def150

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
